AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/aws-sam-helloworldapi-1.0.jar
            Handler: com.harprit.aws.sam.helloworldapi.App::handleRequest
            Runtime: java8
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /hello/{name}
                        Method: get